### ISSUE TITLE
The process won't start for some picture

### ISSUE THREAD

**Issue by darkrain261** [agmmnn/fineartdown#1]
When I try to fetch tiles from of this picture: https://fineartamerica.com/featured/1-yamato-ship-plans-jose-elias-sofia-pereira.html?fbclid=IwAR0DePuHyN80u2cLM3FLJ2qLVpQtbVkH6ybo364BTyfjBn_Px0bwPNmoH9o

The process is stopped after showing resolution, I tried other pictures but they all worked well, only this picture has the problem.
![Screenshot (85)](https://user-images.githubusercontent.com/103837232/227628400-3dd3621d-498d-418b-a01b-1988f0ada2a3.png)

**Comment by agmmnn** [comment]
Hey sorry, I didnt see the notification of this issue. Does this problem still exist? @darkrain261 

edit: I also tried and yes this image has issue.

**Comment by agmmnn** [comment]
fixed in https://github.com/agmmnn/fineartdown/releases/tag/v1.1.2
