### ISSUE TITLE
non technical user-windows, not available to run in win7, said nodejs only support win8.1, when I install node.js v12.12, still not work

### ISSUE THREAD

**Issue by MKateVogel** [agmmnn/fineartdown#4]
non technical user-windows, not available to run in win7, said nodejs only support win8.1, when I install node.js v12.12, still not work

**Comment by agmmnn** [comment]
actually after installing node.js you can use,
`npm install -g fineartdown`

did you tried?

**Comment by MKateVogel** [comment]
i upgrade my node.js to 16 in my win 7, and use cmd to run the exe, but error below.
![Error](https://github.com/agmmnn/fineartdown/assets/134188827/d2ec44ac-8878-43f2-9044-5749ab331f2f)

**Comment by MKateVogel** [comment]
Is there possible to release a new version for win 7 64, and can be run by original Powershell without install or upgrade node.js? This is very helpful for program idiot like me.

**Comment by agmmnn** [comment]
Hey, I'm trying to understand the problem. Here, I used the "node-fetch" library instead of the "built-in fetch library", can you try this? [fineartdown-win.zip](https://github.com/agmmnn/fineartdown/files/11524450/fineartdown-win.zip)

(I had to archive it twice because of the github's "file size limit", sorry)

**Comment by MKateVogel** [comment]
i tried your new [fineartdown-win.zip] by cmd, and new error below:

Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

D:\桌面\Abstract\fineartdown-win>set NODE_SKIP_PLATFORM_CHECK=1

D:\桌面\Abstract\fineartdown-win>node -v
v16.15.1

D:\桌面\Abstract\fineartdown-win>npm -v
8.11.0

D:\桌面\Abstract\fineartdown-win>fineartdown-win https://photos.com/featured/1-s
upertrees-in-gardens-by-the-bay-eternity-in-an-instant.html
Supertrees In  Gardens By The Bay by Eternity In An Instant

C:\snapshot\fineartdown-master\node_modules\.pnpm\node-fetch@2.6.9\node_modules\
node-fetch\lib\index.js:1505
                        reject(new FetchError(`request to ${request.url} failed,
 reason: ${err.message}`, 'system', err));
                               ^
FetchError: request to https://fineartamerica.com/showpreviewimage.php?artworkid
=25604032 failed, reason: connect ETIMEDOUT 75.126.115.192:443
    at ClientRequest.<anonymous> (C:\snapshot\fineartdown-master\node_modules\.p
npm\node-fetch@2.6.9\node_modules\node-fetch\lib\index.js:1505:11)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}

D:\桌面\Abstract\fineartdown-win>

**Comment by agmmnn** [comment]
maybe there is a country-based problem, can you reach this url without any problem? [https://fineartamerica.com/showpreviewimage.php?artworkid=25604032](https://fineartamerica.com/showpreviewimage.php?artworkid=25604032)

(btw, here is the full output of the image: https://i.imgur.com/RyokEhk.jpeg)

**Comment by MKateVogel** [comment]
you are right, we are not available to visit https://fineartamerica.com directly.
I have to use VPN in USA IP, and tried to open the link you provided, and it showed as below
![1](https://github.com/agmmnn/fineartdown/assets/134188827/029aa08b-ed5e-4a4b-acb2-a4a902568035)

So can this problem be solved? :(

**Comment by agmmnn** [comment]
well, a workaround possible but can you reach this tile url?

https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=25604032&widthmedium=780&heightmedium=520&x=300&y=100&domainUrl=photos.com

**Comment by MKateVogel** [comment]
> well, a workaround possible but can you reach this tile url?
> 
> https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=25604032&widthmedium=780&heightmedium=520&x=300&y=100&domainUrl=photos.com

yes, it can be open by using VPN
![2](https://github.com/agmmnn/fineartdown/assets/134188827/730d8cf9-d844-4c90-a3f3-d0fef6fc8dd6)

**Comment by agmmnn** [comment]
If you can access it *without* vpn I can make a workaround but not if you can only access it with vpn. Because the tiles are hosted on the **fineartamerica** server.

You can download it without any problem using VPN, right? In this case, no other solution is possible.

**Comment by MKateVogel** [comment]
I can't access this link without VPN:
https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=25604032&widthmedium=780&heightmedium=520&x=300&y=100&domainUrl=photos.com
I can only access it with VPN. China area was blocked by fineartamerica.com these two years.
I believe this software is a great work, and sure lots of people will benefit from it. It's a pity that I can't run it successfully. 
thank you so much for your great job :D

**Comment by agmmnn** [comment]
No problem, thank you. ^_^
